export const ERROR_CODE = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_ALREADY_EXIST: "EMAIL_ALREADY_EXIST",
  INVALID_VERIFICATION_TOKEN: "INVALID_VERIFICATION_TOKEN",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  INVALID_GOOGLE_PROFILE: "INVALID_GOOGLE_PROFILE",
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
